version: '3.5'

services:
          
    library-gateway:
        image: library-gateway
        container_name: library-gateway
        build:
            context: Library.Gateway
            dockerfile: Dockerfile
        ports:
            - "59580:59580"
        expose:
            - 59580
        environment:
            ASPNETCORE_ENVIRONMENT: "Release"
        depends_on:
            - library-hub
            - library-books
            - library-authors
    
    library-authors:
        image: library-authors
        container_name: library-authors
        build:
            context: Library.Authors
            dockerfile: Dockerfile
        ports:
            - "59581:59581"
        expose:
            - 59581
        environment:
            ASPNETCORE_ENVIRONMENT: "Release"
            
    library-books:
        image: library-books
        container_name: library-books
        build:
            context: Library.Books
            dockerfile: Dockerfile
        ports:
            - "59582:59582"
        expose:
            - 59582
        environment:
            ASPNETCORE_ENVIRONMENT: "Release"
            
    library-hub:
        image: library-hub
        container_name: library-hub
        build:
            context: Library.hub
            dockerfile: Dockerfile
        ports:
            - "59583:59583"
        expose:
            - 59583
        environment:
            ASPNETCORE_ENVIRONMENT: "Release"

networks: 
    default:
        external:
            name: "library-network"

    