version: '3.5'

services:
    library-gateway:
        image: library-gateway
        container_name: library-gateway
        build:
            context: Library.Gateway
            dockerfile: Dockerfile
            args:
                CONFIG_PROFILE: "Development"
                PORT: 59580
        environment:
            ASPNETCORE_ENVIRONMENT: "Release"
        ports:
            - "59580:59580"
        expose:
            - 59580
        depends_on:
            - library-auth
            - library-hub
            - library-book
            - library-shop
    
    library-shop:
        image: library-shop
        container_name: library-shop
        build:
            context: Library.Shop
            dockerfile: Dockerfile
            args:
                CONFIG_PROFILE: "Development"
                PORT: 59581
        environment:
            ASPNETCORE_ENVIRONMENT: "Release"
        ports:
            - "59581:59581"
        expose:
            - 59581
                  
    library-book:
        image: library-book
        container_name: library-book
        build:
            context: Library.Books
            dockerfile: Dockerfile
            args:
                CONFIG_PROFILE: "Development"
                PORT: 59582
        environment:
            ASPNETCORE_ENVIRONMENT: "Release"
        ports:
            - "59582:59582"
        expose:
            - 59582
        
    library-hub:
        image: library-hub
        container_name: library-hub
        build:
            context: Library.hub
            dockerfile: Dockerfile
            args:
                CONFIG_PROFILE: "Development"
                PORT: 59583
        environment:
            ASPNETCORE_ENVIRONMENT: "Release"
        ports:
            - "59583:59583"
        expose:
            - 59583
            
    library-auth:
        image: library-auth
        container_name: library-auth
        build:
            context: Library.Auth
            dockerfile: Dockerfile
            args:
                CONFIG_PROFILE: "Development"
                PORT: 59584
        environment:
            ASPNETCORE_ENVIRONMENT: "Release"
        ports:
            - "59584:59584"
        expose:
            - 59584
            
    library-ui:
        image: library-ui
        container_name: library-ui
        build:
            context: library.ui
            dockerfile: dockerfile
            args:
                environment: "prod"
        ports:
            - "4200:4200"
        expose:
            - 4200
        depends_on:
            - library-gateway

networks: 
    default:
        name: "library-network"

    